sortTest: p4.cpp insertionSort.o mergeSort.o quickSort.o
	g++ p4.cpp insertionSort.o mergeSort.o quickSort.o -o sortTest

insertionSort.o: insertionSort.cpp insertionSort.h
	g++ -c insertionSort.cpp

mergeSort.o: mergeSort.cpp mergeSort.h
	g++ -c mergeSort.cpp

quickSort.o: quickSort.cpp quickSort.h
	g++ -c quickSort.cpp

